name: presence_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.8.4
  convex_bottom_bar: ^3.2.0
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get: ^4.6.5
  image_picker: ^1.0.1
  intl: ^0.18.1
  syncfusion_flutter_datepicker: ^22.2.5

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/1.png"
  adaptive_icon_background: "#000000"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
